### ISSUE TITLE
Can you please publish on https://open-vsx.org/? 🧡

### ISSUE THREAD

**Issue by ghuntley** [leveson/vscode-hy#1]
https://twitter.com/juliawritescode/status/1427961236482887684

**Comment by tshakalekholoane** [comment]
Sure, I'll have a look at it.

**Comment by tshakalekholoane** [comment]
[It's up](https://open-vsx.org/extension/TshakaEricLekholoane/hy). Just filed an issue to have the warning removed.

**Comment by ghuntley** [comment]
🧡 thanks.
